name: king_iptv_dashboard
description: King IPTV Admin Dashboard
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0-333.2.beta

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.2
  firebase_storage: ^12.3.7
  firebase_analytics: ^11.3.8
  
  # Utilities
  crypto: ^3.0.3
  file_picker: ^8.1.6
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true